steps:
  - name: node:20
    entrypoint: 'bash'
    env:
      - 'METADATA_URL='
      - 'SEARCH_URL='
      - 'CATALOG_URL='
      - 'ITEM_URL='
    args: ['-c', 'npm i && npm run build:prod']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args: [ 'gsutil', '-m', '-h', 'Cache-Control:no-cache, max-age=0', 'cp','-Z','-r', 'dist/*', 'gs://itembank-search-apps/itembank-search-view/' ]

timeout: 7200s